// <auto-generated>
// Rewired Constants
// This list was generated on 2025-12-10 오후 2:52:28
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts
{
    public static partial class Action
    {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveHorizontal")]
        public const int MoveHorizontal = 0;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveVertical")]
        public const int MoveVertical = 1;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveUp")]
        public const int MoveUp = 28;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIMoveUp")]
        public const int UIMoveUp = 70;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveDown")]
        public const int MoveDown = 29;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIMoveDown")]
        public const int UIMoveDown = 71;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveLeft")]
        public const int MoveLeft = 30;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIMoveLeft")]
        public const int UIMoveLeft = 72;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveRight")]
        public const int MoveRight = 31;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIMoveRight")]
        public const int UIMoveRight = 73;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
        public const int Jump = 2;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Attack")]
        public const int Attack = 3;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "SubAttack")]
        public const int SubAttack = 4;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Cast1")]
        public const int Cast1 = 5;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Cast2")]
        public const int Cast2 = 6;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Cast3")]
        public const int Cast3 = 7;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Cast4")]
        public const int Cast4 = 8;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Portal")]
        public const int Portal = 9;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Potion1")]
        public const int Potion1 = 10;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Interact")]
        public const int Interact = 12;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Dash")]
        public const int Dash = 11;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "OrderInteract")]
        public const int OrderInteract = 65;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "PopupSkill")]
        public const int PopupSkill = 13;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "PopupInventory")]
        public const int PopupInventory = 17;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "PopupItem")]
        public const int PopupItem = 27;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "PopupPause")]
        public const int PopupPause = 39;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UISubmit")]
        public const int UISubmit = 18;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UISubmit2")]
        public const int UISubmit2 = 26;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UICancel")]
        public const int UICancel = 19;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UICursorHorizontal")]
        public const int UICursorHorizontal = 32;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UICursorHorizontal2")]
        public const int UICursorHorizontal2 = 36;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UICursorVertical")]
        public const int UICursorVertical = 33;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UICursorVertical2")]
        public const int UICursorVertical2 = 37;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIHighPrevious")]
        public const int UIHighPrevious = 49;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIHighNext")]
        public const int UIHighNext = 50;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UILowPrevious")]
        public const int UILowPrevious = 34;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UILowNext")]
        public const int UILowNext = 35;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Equip")]
        public const int Equip = 46;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Use")]
        public const int Use = 47;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Discard")]
        public const int Discard = 48;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Range")]
        public const int Range = 51;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Comparison")]
        public const int Comparison = 52;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Sorting")]
        public const int Sorting = 53;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "OpenBook")]
        public const int OpenBook = 63;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Synergy")]
        public const int Synergy = 75;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "KeyBinding")]
        public const int KeyBinding = 56;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Skip")]
        public const int Skip = 78;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIDepthUp")]
        public const int UIDepthUp = 61;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UIDepthDown")]
        public const int UIDepthDown = 62;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "WorldDifficulty")]
        public const int WorldDifficulty = 74;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "CameraUp")]
        public const int CameraUp = 76;

        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "CameraDown")]
        public const int CameraDown = 77;

    }
    public static partial class Category
    {
        public const int Default = 0;

    }
    public static partial class Layout
    {
        public static partial class Joystick
        {
            public const int Default = 0;

        }
        public static partial class Keyboard
        {
            public const int Default = 0;

        }
        public static partial class Mouse
        {
            public const int Default = 0;

        }
        public static partial class CustomController
        {
            public const int Default = 0;

        }
    }
    public static partial class Player
    {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;

        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;

    }
    public static partial class CustomController
    {
    }
    public static partial class LayoutManagerRuleSet
    {
    }
    public static partial class MapEnablerRuleSet
    {
    }
}
